CONFIG += QGC_DISABLE_CUSTOM_BUILD
CONFIG += QGC_DISABLE_PX4_PLUGIN
CONFIG += QGC_DISABLE_PX4_PLUGIN_FACTORY

DEFINES += QGC_DISABLE_BLUETOOTH
DEFINES += QGC_DISABLE_UVC

CONFIG += DISABLE_VIDEOSTREAMING
CONFIG += QGC_DISABLE_BUILD_SETUP

DEFINES += DISABLE_SPEECH

DEFINES += DISABLE_ZEROCONF
